version: "3.9"

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: frontend
    env_file:
      - .env
    ports:
      - "3000:3000"
    restart: unless-stopped
